 # The workflow will Build and Deploy
 name: Build and Deploy
 on: 
   workflow_dispatch:
     inputs:
       branch:
         description: Branch to build
         required: true
         default: 'releases/202'
       heroku_app_name:
         description: Heroku app name for deployment
       heroku_oauth_token:
         description: Generate a client Heroku Oauth token via Heroku CLI using 'heroku:authorizations create'
         default: ''
       # clear_and_install_buildpacks:
       #   description: Do you want to clear and install buildpacks [Y/N]
       #   default: 'Y'
 
 jobs:
   build:
     name: Build and Deploy
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.branch }}
 
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '14'
 
       - name: Install Dependencies
         run: npm install
 
       - name: Build Backend Code
         run: npm run build
 
       - run: heroku plugins:install node
 
       # - name: Clear and Install Buildpacks
       #   if: ${{ github.event.inputs.clear_and_install_buildpacks == 'Y'}}
       #   run: |
       #     HEROKU_API_KEY='${{ github.event.inputs.heroku_oauth_token }}' heroku buildpacks:clear --app '${{ github.event.inputs.heroku_app_name }}'
       #     HEROKU_API_KEY='${{ github.event.inputs.heroku_oauth_token }}' heroku buildpacks:add heroku/nodejs --app '${{ github.event.inputs.heroku_app_name }}'
           
       - name: Deploy to heroku environment
         run: |
           git remote add heroku https://git.heroku.com/${{ github.event.inputs.heroku_app_name }}.git
           git push heroku main
         env:
           HEROKU_API_KEY: ${{ github.event.inputs.heroku_oauth_token }}
 
 
       # Mark the job as succeeded if all the previous steps succeeded
       - name: Mark job as succeeded if all steps succeeded
         if: success()
         run: echo "All tasks succeeded"
         
       - name: Tasks failed
         if: failure()
         run: echo "Tasks failed"
